/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author mamad
 */
public class board2 extends javax.swing.JFrame {
File accunt = new File("accunt.txt");
File accuntnow = new File("accuntnow.txt");
 BufferedReader buffer;
 boolean a=false;
       boolean b=false;
  String user,pass;
  String [][] accuntt=new String[100][3];
  String line;
  int d=0;
  int wac;
    public board2() {
        
        setPreferredSize(new Dimension(1380, 810));
        initComponents();
          setLocationRelativeTo(null);
        accuntnow.deleteOnExit();
          try {
             buffer = new BufferedReader(new FileReader(accunt));
              line=buffer.readLine();
             for(int i=0;line!=null;i++){
                 accuntt[i]=line.split("#");
                 d++;
                  line=buffer.readLine();
             }
         } catch (Exception ex) {
             Logger.getLogger(Board.class.getName()).log(Level.SEVERE, null, ex);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(440, 360, 220, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(440, 210, 230, 50);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(444, 414, 220, 40);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\proje\\bilde.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 450, 150, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\proje\\exit.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 700, 160, 40);

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\proje\\enter.jpg")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(430, 450, 130, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\proje\\2.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -20, 1410, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        board1 board1=new board1();
        board1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        board3 board3=new board3();
        board3.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       user=jTextField1.getText();
       
       for(int i=0;i<=d;i++){
           if(user.equals(accuntt[i][1])){
               wac=i;
                a=true;
               break;
           }
       }
       if(a==false){
           jLabel1.setText("اکانت وجود ندار");
       }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        pass=jPasswordField1.getText();
        
       for(int i=0;i<=d;i++){
           if(pass.equals(accuntt[i][2])){
                b=true;
               break;
           }
       }
       if(b==false){
           jLabel1.setText("پسورد اشتباه است");
       }
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(a && b){
            jLabel1.setText("شما وارد شدید");
        }
        try{
         if (!accuntnow.exists()) {
                   accuntnow.createNewFile();}
                   BufferedWriter buffer = new BufferedWriter(new FileWriter(accuntnow));
              buffer = new BufferedWriter(new FileWriter("accuntnow.txt"));
              buffer.write(accuntt[wac][0]+"#"+accuntt[wac][1]+"#"+accuntt[wac][2]+"\n");
              buffer.close();
              
          } catch (IOException e) {
              e.printStackTrace();
          }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
