/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.Arrays;

/**
 *
 * @author mamad
 */
public class board4 extends javax.swing.JFrame {

    /**
     * Creates new form board4
     */
    File accunt = new File("accunt.txt");
File accuntnow = new File("accuntnow.txt");
String [][]all=new String[100][3];

String[]now=new String[3];
String[]s=new String[10];
String[]m=new String[10];
String line;
int d=0,j,k=0;

String intt;
    public board4() {
        accuntnow.deleteOnExit();
        
        int[]point=new int[100];
         try {
             
     BufferedReader   bufferacc = new BufferedReader(new FileReader(accuntnow));
                 now=bufferacc.readLine().split("#");
            
              
             BufferedReader buffer = new BufferedReader(new FileReader(accunt));
              line=buffer.readLine();
             for(int i=0;line!="\n";i++){
                 all[i]=line.split("#");
                 d++;
                 point[i]=Integer.parseInt(all[i][0]);
                
                
                  line=buffer.readLine();
             } buffer.close();
           bufferacc.close();}

             
     catch (Exception ex) {
    }
        setPreferredSize(new Dimension(1380, 810));
        initComponents();
          setLocationRelativeTo(null);
         Arrays.sort(point);
        for(int i=99;i>99-d;i--){
           
            for(int e=0;true;e++){
                   
                j=Integer.parseInt(all[e][0]);
                if(point[i]==j){
                    s[k]=all[e][1];
                    m[k]=all[e][0];
                    k++;
                    break;
                }
            }
        }
       
//        System.out.println(s);
//      jLabel1.setText(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(570, 340, 300, 60);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\snake\\snake\\online.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(693, 693, 130, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\snake\\snake\\exit.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(83, 693, 160, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 200, 320, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 240, 320, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 280, 320, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 320, 310, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 360, 320, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(60, 390, 320, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 430, 320, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 480, 330, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(60, 520, 320, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 560, 320, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 200, 80, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(420, 240, 80, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 280, 80, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(420, 320, 80, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(420, 360, 80, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(420, 400, 80, 40);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(430, 430, 80, 40);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(430, 480, 70, 40);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(430, 510, 70, 40);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(430, 560, 70, 50);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(630, 544, 230, 70);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\mamad\\Desktop\\snake\\snake\\4.jpg")); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(0, -6, 1430, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       board1 board1=new board1();
       this.setVisible(false);
       board1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        board5 board5=new board5();
        this.setVisible(false);
        board5.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       jLabel23.setText(now[0]);
        jLabel5.setText(s[0]);
        jLabel6.setText(s[1]);
        jLabel7.setText(s[2]);
        jLabel8.setText(s[3]);
        jLabel9.setText(s[4]);
        jLabel10.setText(s[5]);
        jLabel11.setText(s[6]);
        jLabel12.setText(s[7]);
        jLabel13.setText(s[8]);
        jLabel14.setText(s[9]);
         jLabel3.setText(m[0]);
        jLabel4.setText(m[1]);
        jLabel15.setText(m[2]);
        jLabel16.setText(m[3]);
        jLabel17.setText(m[4]);
        jLabel18.setText(m[5]);
        jLabel19.setText(m[6]);
        jLabel20.setText(m[7]);
        jLabel21.setText(m[8]);
        jLabel22.setText(m[9]);
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(board4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(board4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(board4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(board4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new board4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
